### ISSUE TITLE
Can't render fresh template

### ISSUE THREAD

**Issue by kennethlarsen** [empress/create-empress-blog-template#1]
When creating a completely new empress template and run `ember s` I get this error: https://github.com/ember-fastboot/ember-cli-fastboot/issues/711

If I pin `ember-cli-fastboot` to `2.1.1` it works.

**Comment by mansona** [comment]
and it looks like they fixed this upstream 🎉 😂 

My favourite type of bug is one that someone else fixes for you 🎉 Also I just released a new version of one of the things that powers the create-empress-blog-template and it removes an annoying deprecation for you 👍 let me know if you need any more help
